Redesign config architecture
dsx-tech/Blockchain-Payment-System pull request #12
Opened 2019-11-18 14:56 UTC by DmitryPogrebnoy

2019-11-18 15:21 UTC, skoret reviewed
выглядит славно
и даже придумалось, что можно обсудить

2019-11-18 15:28 UTC, skoret requested changes
предлагаю сохранять простоту в именовании пакетов, давай `currencyconfig` в `currencies` переименуем. проблем с трактовкой смысла не будет, т.к. структура директорий вполне себе всё объясняет

2019-11-18 15:28 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +            coinConfig.validateRequired()
только для coinConfig необходимо проводить валидацию?
во всех остальных конфигах ведь тоже все параметры required

2019-11-18 15:28 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val invoiceProcessorConfig = with(Config()){
было бы здорово когда-нибудь добраться до код-стайла проекта и закоммитить его в репозиторий, но это когда-нибудь и обязательно
пока предлагаю перед открывающими фигурными скобками ставить пробелы, единообразия для

2019-11-18 16:35 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +            coinConfig.validateRequired()
Действительно, пропустил(

2019-11-18 16:35 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val invoiceProcessorConfig = with(Config()){
Принято)

2019-11-18 18:37 UTC, phil-dolgolev submitted a review, later dismissed

2019-11-18 22:33 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val invoiceProcessorConfig = with(Config()){
и остальные файлы тоже, пожалуйста

2019-11-19 16:06 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val invoiceProcessorConfig = with(Config()){
Готово

2019-11-19 18:53 UTC, skoret approved these changes

2019-11-19 18:53 UTC, merged