Architecture improvement
dsx-tech/Blockchain-Payment-System pull request #14
Opened 2019-11-19 19:12 UTC by DmitryPogrebnoy

Переименовал CoinClient в Coin, BlockchainListener в Explorer и наследуемые от них классы соответственно. Перетащил из arch ветки Coins класс. Немного изменил конфиги.

2019-11-20 10:02 UTC, skoret requested changes

2019-11-20 10:02 UTC, skoret commented on src/main/kotlin/dsx/bps/config/currencies/BtcConfig.kt
>  object BtcConfig: ConfigSpec("btcConfig") {
коли стараемя сохранить простоту и последовательность в нейминге, то в "btcConfig" конфиг выглядит лишним

2019-11-20 10:02 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val emitters = coins.coins.values.map { it.getTxEmitter() }
мб добавить в Coins метод для получения эммитеров (всех или по конкретной валюте)?
коинс.коинс смущает немного

2019-11-20 10:02 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
>              addSpec(BtcConfig)
initConfig используется здесь (и в остальных коинах) только чтобы попасть в with()
в конструкторе Coins похожая инициализация конфига выглядит лучше

- [x] поправить лишние переменные в коинах

2019-11-20 10:02 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +        val user = config[BtcConfig.Coin.user]
конструктор, принимающий путь к конфигу отличается от конструктора, принимающего объект конфига только тем, что подгружает файл в объект, а дальше логика одинаковая
причём все коин-клиенты грузят конфиг из файла одинаково

предлагаю в Coin добавить статик-метод, который по пути и спеке будет подгружать конфиг, валидировать его и возвращать
тогда конструктор, принимающий путь к конфигу, будет просто перенаправлять вызов в конструктор с подгруженным конфигом

- [x] переиспользовать конструктор с конфигом

2019-11-20 12:48 UTC, phil-dolgolev reviewed
С ренеймингами нужно быть аккуратнее

Если явно что-то плохо названо - то стоит менять, в противном случае обычно лучше забить, потому что сколько людей - столько мнений, и при постоянном ренейминге будет потом сложнее общаться на одном языке всем

2019-11-20 12:48 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +class Coins {
Это скорее CoinsRouter/Manager/etc

2019-11-20 12:48 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +    val coins: Map<Currency, Coin>
enabledCoins?

2019-11-20 12:48 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +        val coin = getCoin(currency)
Нанопридирка, но кажется что вполне себе инлайн тут можно все дергать, а не разбивать на 2 строчки (это про все методы в этом классе)

2019-11-20 12:48 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
Тогда можно уж все вызовы обернуть в такой tryCatch

2019-11-21 12:03 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/config/currencies/BtcConfig.kt
>  object BtcConfig: ConfigSpec("btcConfig") {
"btcConfig" -> "BTC" и аналогичные так же

2019-11-21 12:04 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
>              addSpec(BtcConfig)
Поправил

2019-11-21 12:15 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        val emitters = coins.coins.values.map { it.getTxEmitter() }
Добавил в Coins метод получения всех эмиттеров. Получение эмиттера конкретной криптовалюты пока негде использовать, как понадобиться так и реализую.

2019-11-21 12:34 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +        val user = config[BtcConfig.Coin.user]
Выкинул конструктор конкретного Coin'a по пути до конфига т.к. он нигде не используется. Убрал проверку конфига в конструкторе конкретного Coin'a по конфигу. Перенес логику CoinFactory в CoinsManager, кажется это лучше отвечает принципу инкапсуляции.

2019-11-21 12:34 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +class Coins {
Будет CoinsManager

2019-11-21 12:34 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +    val coins: Map<Currency, Coin>
Так и правда лучше)

2019-11-21 12:35 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +        val coin = getCoin(currency)
Действительно

2019-11-21 12:57 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
Вот здесь я немного не понимаю.  @skoret что будет если запросить транзакцию по хешу которой нет в ноде? Код ответа будет 200 или другой?

2019-11-22 03:31 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
зависит от конкретной валюты
там даже не http-коды, а какой-нибудь json описывающий ошибку о ненайденной/несуществующей транзе
тут надо смотреть в CoinConnector.parseResponse
если на запрос вернулось не то, что мы ожидаем, сейчас бросается эксепшн

конкретно этот try-catch здесь, чтобы можно было лист хэшей замапить в лист вернувшихся транзакций, и не отвалиться на одной ненайденной

возможно, стоит пересмотреть решение выброса исключения в коннекторе на возвращение null

2019-11-22 04:10 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +        val user = config[BtcConfig.Coin.user]
решение добавить в Currency метод по созданию соответствующего коин-клиента хорошо, ровно как и фабрика, тем, что в коин-менеджере мы создаём любой клиент одной строчкой и добавление новых валют не заставит нас что-то менять в здесь
 
но сами currency ходят вообще по всей системе, в том числе появляются в invoice/paymentProcessor'ах, которые вроде как не должны знать про CoinClient'ов
а теперь в теории они могут создавать новые инстансы коин-клиентов, передав в currency спеку. то бишь модули начали пересекаться, инкапсуляция ломается

фабрика хоть и с одним статик-методом, но аналогично абстрактному Currency.createCoin обязывала разработчика добавить в неё пункт с созданием нового клиента, потому что там был switch (простите, when) по енуму
Currency больше про данные, чем про какую-то функциональность, — идентификатор валюты

2019-11-22 10:34 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +        val user = config[BtcConfig.Coin.user]
Кажется естественным, что класс валюты может создать свой Coin. 
То что currency ходят по всей системе настораживает, но с вариантом фабрики ничего не мешает "выстрелить в ногу" - вызвать фабричный метод, т.к. в currency уже есть необходимый ConfigSpec. Кроме того вызов фабричной функции происходит в одном месте и в обозримом будущем ничего не изменится.

Представим что добавляем новую валюту. Объясни, пожалуйста, разницу между тем что мы дописываем еще один вариант в when в конструкторе CoinsManager с тем что мы дописываем еще один вариант в when в фабричной функции.

Альтернативный вариант(и кажется лучший) - можно перенести when в конструктор CoinsManager. Тем самым уберем синтетический фабричный класс и заберем у currency возможность создавать коины.

2019-11-22 10:50 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        emitter = coinsManager.getAllEmitters().observeOn(Schedulers.from(threadPool))
Кстати, вопрос на подумать, а почему именно такое количество потоков выбирается ?)

2019-11-22 10:50 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +    constructor(coinsMap: CoinsManager, invoiceProcessor: InvoiceProcessor,
наверное тут продолбался ренейминг

2019-11-22 14:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
кстати, здесь инлайн getCoin(currency) не подходит под общую схему
т.к. если мы во всех остальных методах отвалимся с эксепшеном из-за невключённой валюты, то тут вернём пустой список

2019-11-22 15:14 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +        val user = config[BtcConfig.Coin.user]
это не должно настораживать, т.к. currency — идентификатор валюты. насторожит, если у нас для одной валюты будет несколько разных типов-идентификаторов
наличие в них спеков — вариант рабочий, но по названной тобою причине не особо идеологичный, да
с фабрикой выстрел в ногу хэндлится тем, что фабрика ограничена модулем crypto и до неё нельзя достать из core
размещение when в конструкторе аналогично методу фабрики
согласен, выглядит довольно подходяще

2019-11-22 17:47 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        emitter = coinsManager.getAllEmitters().observeOn(Schedulers.from(threadPool))
Берем все что доступно данному процессу)
Количество потоков возможно тоже стоит брать из конфига?

2019-11-22 17:47 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +    constructor(coinsMap: CoinsManager, invoiceProcessor: InvoiceProcessor,
Де, бывает

2019-11-22 20:25 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
Действительно, ловится не нужная ошибка. Видимо стоит ловить только свои ошибки.
Почему нужно не отваливаться с ошибкой если хоть одна транзакция из списка не найдена?

2019-11-23 15:44 UTC, DmitryPogrebnoy commented
Добавил свои базовые исключения. Добавил настройку количества потоков для invoice observer из конфига.

2019-11-25 07:47 UTC, phil-dolgolev approved these changes

2019-11-25 07:47 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        emitter = coinsManager.getAllEmitters().observeOn(Schedulers.from(threadPool))
Это имеет смысл если на хостовой машине только твое приложение, а задачи CPU-heavy

IO-операции - вот совсем не CPU-heavy (а тут вроде много как раз IO) 

И кстати я понял, что не очень разобрался что здесь и на каком потоке обрабатывается, надо будет обсудить вживую наверное

2019-11-25 08:58 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/Coins.kt
> +                    println(ex.message)
хотелось получить то, что получилось, а не отваливаться из-за одной пропавшей
возможно, обрабатывать здесь по-другому
но это уже на следующий раз

2019-11-25 08:59 UTC, skoret approved these changes

2019-11-26 13:01 UTC, merged