DatabaseStructure
dsx-tech/Blockchain-Payment-System pull request #15
Opened 2019-11-29 02:18 UTC by artemlunev2000

еще не исправил то, что услышал в пятницу

2019-12-04 15:58 UTC, skoret requested changes
Предлагаю в целях недвусмысленного нэйминга называть все табличные классы InvoiceTable
все энтити классы — InvoiceEntity

2019-12-04 16:02 UTC, skoret requested changes
`+ хочется, чтобы названия самих файлов совпадали с названиями содержащихся в них классов
// если классов несколько, то имя файла == имя самого семантически важного класса

2019-12-06 05:01 UTC, dz-dsxt commented on src/main/kotlin/dsx/bps/DBclasses/BtcTxTable.kt
> +    val fee: Column<String?> = varchar("fee", 100).nullable()
Почему мы числа в строках храним?
Есть ведь https://dev.mysql.com/doc/refman/8.0/en/precision-math-decimal-characteristics.html

2019-12-06 05:03 UTC, dz-dsxt commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +            user = "root", password = "root")
Креды к базе надо сразу в настройки выносить (url, user, password). Так же стоит в connectionString явно указывать кодировку

2019-12-06 05:14 UTC, dz-dsxt commented on build.gradle
> +
Почему в зависимостях не появилось jdbc драйвера?

2019-12-06 05:16 UTC, dz-dsxt commented
Стоило бы сразу добавить возможность запуска на h2 базе, чтоб удобнее отлаживаться было

2019-12-06 05:17 UTC, dz-dsxt commented
Ещё нужно добавить скриптов, которые смогут пустую базу заполнить табличками

2019-12-06 08:50 UTC, phil-dolgolev reviewed
И сразу надо наваять тесты либо с in-memory базой, либо с testcontainers, чтоб огрести все проблемы

2020-02-18 13:49 UTC, phil-dolgolev commented
Создан аналогичный

2020-02-18 13:49 UTC, closed without merging