Bps 25
dsx-tech/Blockchain-Payment-System pull request #16
Opened 2019-12-04 15:26 UTC by siandreev

Coin and Explorer ether realisation added

2019-12-04 15:37 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +     * @param txid IxId object ( {hash : String, index : Int} )
IxTx

2019-12-04 15:39 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +                    this.status() == TxStatus.VALIDATING -> hexToWei(ethTx.gasPrice)
предлагаю енумчики сравнивать конструкцией
```
when this.status() {
    TxStatus.VALIDATING...
```

2019-12-06 09:28 UTC, phil-dolgolev requested changes

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +     * @return account balance in ether (15 signs).
Может 15 конфирмейшенов?

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +                return when {
Выглядит как чересчур фанатство when, тут даже старый добрый тернарный оператор отлично зайдет :)

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +            override fun currency() = Currency.ETH
Я правильно понимаю, что здесь создается анонимный класс каждый раз? 
Довольно странная штука, почему не запилен именно класс для этого дела, реализующий интерфейс?

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +        val txHash = rpc.sendTransaction(__from = accountAddress, __to = address, __value = amount)
На самом деле это очень упрощенная реализация, которую точно надо будет менять

1) Nonce нужно контролировать на своей стороне
2) Нужно рассматривать вариант, когда sendTransaction отвалился с ошибкой, ибо по факту транзакция может уйти в сеть, да только мы не узнаем об этом, что приведет к даблспенду. 
3) Идеально - сделать подпись транзакции в приложении, а не разлачивать в ноде кошелек. И вообще, надо идти к тому, чтоб в ноде никакого контексте не было и мы на него не пологались, кошельки храним отдельно

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthConverter.kt
> +fun hexToEth(hex: String): BigDecimal {
Web3j  как раз позволит не реализовывать такие штуки самому с нуля

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        viewed.add(last.hash)
При перезапусках мы не заполняем историю? Это надо как-то обойти

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +                    viewed.add(new.hash)
Добавление сразу во viewed означает, что если мы свалимся с ошибкой дальше, то у нас потенциально возникает пропуск блоков, или я что-то не так понял?

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +class EthRpc(url: String) : JsonRpcHttpClient(url) {
Нужно рассмотреть замену на Web3j

2019-12-06 09:28 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/rpc/JsonRpcHttpClient.kt
> +            var cleanedParams = params.filter { x->x != "\"jsonrpc\":\"2.0\""} //говнокод
Отличный PR :D
Удаляй "говнокод" :)

2019-12-06 09:28 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +internal class EthRpcTest {
Вот для этого нам и нужны testcontainers, чтобы эти тесты на только руками можно было запускать на определенном локальном энвайроменте, но и на CI

2019-12-13 23:26 UTC, skoret requested changes
- Отвечаем и резолвим комменты на уже исправленные замечания, чтобы трекать прогресс
- Если исправления для какого-то замечания не нужны, объясняем/спрашиваем/обсуждаем так же в комментах
- Когда-нибудь я обязательно залью код-стайл конфиг в репозиторий, а пока перед коммитом/пушем/пулл-реквестом прошу пробегаться по всему новому и производить косметический рефакторинг. Ориентироваться можно на уже готовые модули (особое внимание на необходимые/лишние пробелы, переносы строк, также подсказки IDE часто очень полезны)

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        __nonce: BigInteger = getTransactionCount(__from)
нам правда необходимы двойные подчёркивания здесь?
по код-стайлу чуть-чуть: если аргументы в несколько строчек, то запятые в конце

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/rpc/JsonRpcHttpClient.kt
> +      //  else {
- [ ] ненужное — удаляем, для будущих доделок — `// TODO: <message>`

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/datamodel/EthTxInfo.kt
> +    // val nonce: String //а лучше добавить с теми же остальными полями но в другом классе
`// TODO: <message in english>`

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/rpc/JsonRpcHttpClient.kt
> +        conn.setRequestProperty("Content-Type", "application/json") //только для eth, говнокод
- [ ] вынести в EthRpc

для референса смотри в 
1) [BtcRpc#L14](https://github.com/dsx-tech/Blockchain-Payment-System/blob/master/src/main/kotlin/dsx/bps/crypto/btc/BtcRpc.kt#L14)
2) [JsonRpcHttpClient#L63](https://github.com/dsx-tech/Blockchain-Payment-System/blob/master/src/main/kotlin/dsx/bps/rpc/JsonRpcHttpClient.kt#L63)

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/core/datamodel/Currency.kt
> +    ETH{
- [ ] пробелы между именем и скобкой

// для каждой валюты

2019-12-13 23:26 UTC, skoret commented on build.gradle
> +
почисти, пожалуйста, новые лишние пустые линии

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/common/Coin.kt
> +    protected abstract val rpc: Any
возможно, стоит завести интерфейс Connector (или что-то в этом роде)
пусть даже пустой без методов
здесь, в Coin, rpc будет типа этого интерфейса
а дальше и JsonRpcHttpClient, и EthRpc будут его "реализовывать"
так мы явно будем сигнализировать, что это коннектор к ноде, а не что-Any-угодно

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +        return EthTxStandart(ethTx, rpc,confirmations)
в ответ @phil-dolgolev на коммент, относительно создания объекта, а не отдельного класса

в таких местах создавались именно объекты, а не классы, т.к. для конвертации специфичных EthTx (и для других валют аналогично) в обобщённый вид Tx необходима дополнительная информация, которой может обладать CoinClient
нр, те же вызовы rpc клиента, чтобы понять, сколько у нас подтверждений
если писать реализацию интерфейса Tx  для каждого класса, то это должен быть data class
который из себя — исключительно данные, без логики
отдавать в такой класс ссылку на rpc, да ещё и с публичным доступом, совсем не хочется

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +        nonce ++ // разработать безопасную работу с nonce
ещё раз: такие штуки помечаем как `// TODO: <comment in english>`

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +    fun getLatestBlock(): org.web3j.protocol.core.methods.response.EthBlock.Block {
одни типы (нр, Transaction из web3j) импортированы
другие используются так, как здесь
стремимся к однообразию → юзаем импорты как и везде
**upd:** в остальных файлах в пулл реквесте тоже

2019-12-13 23:26 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +                             gasLimit : BigInteger = 90000.toBigInteger(), toAddress : String,
магические числа лучше выносить в константы с поясняющим их названием

2020-02-27 08:59 UTC, phil-dolgolev commented
Не актуален

2020-02-27 08:59 UTC, closed without merging