Database
dsx-tech/Blockchain-Payment-System pull request #17
Opened 2020-02-11 16:22 UTC by artemlunev2000

2020-02-12 10:43 UTC, phil-dolgolev commented
Нейминг потерян, рекомендую опять договоренности перечитать  :) 
И в дальнейшем им следовать

2020-02-12 11:14 UTC, phil-dolgolev requested changes
Еще обкашляем схему и некоторые спайси-моменты, но в целом направление верное.

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
А можно это везде енамами протащить? А то неудобно потом раскапывать и понимать что происходит :)

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +class BtcService {
Это было нужно для своих тестов каких-то?

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/Datasource.kt
> +        config.driverClassName = "org.h2.Driver"
Точно выглядит как настройки, которые надо повыносить из кода

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +        Database.connect(Datasource().getHicari())
Есть подозрения что не правильно пользуемся либой, возможно не каждый раз нужно коннектиться, нужно уточнить этот момент

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +            unpaidInv.forEach { unpaid.add(it.invoiceId) }
Странная штука с транзакциями тут тоже :)

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +            else -> Currency.TRX // else is necessarily, throw exception?(which never happen if all right)
exception точно

2020-02-12 11:14 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/InvoiceProcessor.kt
> +                            inv.txids.remove(tx.txid()) // do we need to store rejected transactions in db?
Как минимум статус какой-то проставить в БД должны, удалять физически - хз, можно для истории оставлять

2020-02-14 07:09 UTC, phil-dolgolev requested changes

2020-02-14 07:09 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        Database.connect(Datasource().getHicari(connectionURL, driver))
Выглядит так, что должен быть везде один Datasource, а не в каждом сервисе создавать свой.

2020-02-14 07:09 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        Database.connect(Datasource().getHicari(connectionURL, driver))
https://github.com/JetBrains/Exposed/wiki/DataBase-and-DataSource

2020-02-19 07:58 UTC, phil-dolgolev requested changes

2020-02-19 07:58 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/Datasource.kt
> +    companion object{
Технически стало лучше, но кажется что все таки в одном месте должен инициализироваться Datasource и везде его готовый передавать, а не тянуть настройки connectionUrl, driver

2020-02-19 07:58 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        val new = TxService(coin.config[DatabaseConfig.connectionURL], coin.config[DatabaseConfig.driver]).add(tx.status().toString(), tx.destination(), tx.tag(), tx.amount(),
Здесь тоже странновато будет.
1) Отличная подсказка от IDEA - прячешь уже существующую переменную new
2) TxService тоже выглядит как синглтон, который один раз инитится, а дальше уже готовый инстанс передается, и создавать каждый раз его имхо перебор

2020-02-27 21:20 UTC, skoret commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
для payable type, tx status, currency и всех enum типов, которыми мы оперируем хочется иметь некий "type safe" подход, чтобы читать да записывать спокойно
наверно, стоит посмотреть [exposed/wiki/datatypes](https://github.com/JetBrains/Exposed/wiki/DataTypes) и [в комменты к issue](https://github.com/JetBrains/Exposed/issues/191)
мб @phil-dolgolev подскажет (асинхронно/через тг), как с этим справляются в продакшене

2020-02-27 22:14 UTC, skoret requested changes

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBclasses/InvoiceEntity.kt
> +    var received by InvoiceTable.received// кол во адресс валюта
комментарий выглядит как подсказка для автора кода, но не поясняющей что-либо подсказкой для читателя
кажется, что он и не нужен здесь

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBclasses/BtcTxEntity.kt
> +    var Tx by TxEntity referencedOn BtcTxTable.TxId
предлагаю сохранять стиль нейминга, коль начали с именами со строчных букв, то и `tx` будет славно смотреться

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +             _tx: TxEntity): BtcTxEntity {
подчёркивания выглядят излишне, т.к. при создании entity мы можем обращаться к её полям через `it` или `this` (точно не вспомню сейчас)

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/DatabaseCreation.kt
> +    fun createInvoices() {
это тесты? будет полезно, если они проверят хотя бы отсутствие исключений и будут жить в `src/test`
либо стоит чуть внимательнее проверять то, что собирается быть закоммиченным/запушенным с:

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/Datasource.kt
> +    companion object{
по-моему, уже обсудили это на встрече, но законспектирую (исправляйте, предлагайте!)

решение со статик-переменной, к которой у всех есть доступ — безусловно рабочее
но стоит всё же рассмотреть вариант реализации с созданием `Datasource` (например, в менеджере) и последующей передачей его в конструкторы тем, кому он нужен (`InvoiceProcessor`, `PaymentProcessor`, что там ещё у нас есть)
это, например, даст нам гибкость в тестировании тех же процессоров, т.к. мы сможем мокать `Datasource`

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +            unpaidInv.forEach { unpaid.add(it.invoiceId) }
кажется, что нет необходимости в конкарренси и транзакционном получении id'шников инвойсов, т.к. мы уже получили сами инвойсы в переменную `unpaidInv` (могу ошибаться, поправьте)
судя по логике, здесь достаточно маппинга из инвойсов в их id, можно будет обойтись без дополнительной переменной

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +    fun getUnpaid(): ConcurrentHashMap.KeySetView<String, Boolean> {
возвращать `ConcurrentHashMap.KeySetView<String, Boolean>` кажется довольно излишним
мб будет достаточно простой мапы или сета пар?

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +    fun getInvoices(): ConcurrentHashMap<String, Invoice> {
здесь тоже должно простой мапы хватить

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/PaymentService.kt
> +            "FAILED" -> PaymentStatus.FAILED
для того, чтобы не мучаться с написанием таких свитчей, стоит разобраться с представлением наших enum в бд

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/TrxService.kt
> +//    }
если этот метод нам не нужен, давайте удалим

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        Datasource.initConnection(databaseConfig)
интересно
`InvoiceProcessor` и `PaymentProcessor` при инициализации создают себе `InvoiceService` и `PaymentService` соответственно, которые в свою очередь уже используют `Datasource` для создания таблиц
но `Datasource.initConnection` вызывается уже после этого
бага или я запутался?
ещё один повод переехать на передачу `Datasource` в конструктор

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/core/PaymentProcessor.kt
> +    private val processing = payService.getStatusedPayments("PROCESSING")
если мы (или не мы) когда-нибудь захотим изменить название статуса, то будет больно — придётся по всему проекту искать вхождения, скажем, `"PENDING"` и заменять его (idea, конечно, поможет, но не во всех кейсах)
у нас ведь есть заданный enum со статусами, а у конкретного статуса как раз можно взять его строковое представление (а мб стоит изменить сигнатуру методов, чтобы они принимали не строки, а сразу значения enum? тогда и реализация самих методов проще станет)

2020-02-27 22:14 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +    private val txService = TxService()
а что, если у нас будет один умный `TxService`, которому explorer'ы смогут скармливать свои транзакции
и он уже в свою очередь будет их рассовывать по необходимым табличкам (сервисам?)
создание `TxService` + `<Currency>Service` в каждом специфичном explorer'е выглядит довольно болезненно

2020-03-01 14:01 UTC, skoret requested changes

2020-03-01 14:01 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +            transaction.amount(), transaction.fee(), transaction.hash(), transaction.index(), transaction.currency().toString())
передавать `Tx` объект в метод `TxService.add(tx)` будет намного приятнее, чем каждый раз самому доставать их этого объекта необходимые параметры

2020-03-01 14:01 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        btcService.add(it.confirmations, blockHash, it.address, newTx)
в `BtcService` мы хотим вместе с транзакцией отдавать хэш блока, в котором она находится (не совсем понимаю, зачем, но мб так задумывалось)
но здесь написано, что для всех новых транзакций мы записываем один и тот же хэш блока
при чём уже просмотренного блока
**TODO**: пересмотреть необходимость хэша блока в базе данных, либо реализовать получение _правильного_ хэша блока для каждой транзакции отдельно

2020-03-02 06:11 UTC, phil-dolgolev requested changes

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
В принципе @skoret скинул все что нужно, осталось только в PayableTable разобраться с колонкой, сделать её типизированной.

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/Datasource.kt
> +    companion object{
Тут кажется все сделано @artemlunev2000 ? 
Вообще старайся отписывать по мере фиксов, а то непонятно и нужно догадываться :)

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +    fun getInvoices(): ConcurrentHashMap<String, Invoice> {
@artemlunev2000 чуток переформулирую на всякий
Нужно всегда стараться оперировать наиболее общими интерфейсами где это возможно, позволяет потом куда больше свободы в реализации, и легко менять одно на другое. А так неявно это провоцирует дальнейшее использование за пределами этого класса какой-то специфики именно ConcurrentHashMap, когда на самом деле тут хочется лишь key-value мапинг, не более.

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/PaymentProcessor.kt
> +    private val processing = payService.getStatusedPayments("PROCESSING")
Как по мне - это все то же отстреливание нетипизированного enum-а в базе. Учитывая сколько проблем уже сейчас это порождает, must have пофиксить в этом PR

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +            transaction.amount(), transaction.fee(), transaction.hash(), transaction.index(), transaction.currency().toString())
На самом деле - зависит. Вдруг человек хотел абстрагироваться :) 
@artemlunev2000 расскажи что тебя привело к такому

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +    private val txService = TxService()
Можно тикетос на потом завести, хочется уже замержить это дело, а то зависли надолго :)

2020-03-02 06:11 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        btcService.add(it.confirmations, blockHash, it.address, newTx)
Нужно имхо понять/вспомнить зачем тут хэш блока. С точки зрения бизнеса - не нужон, с точки зрения транзакции - тоже штука сбоку. Возможно надо выпилть.

2020-03-05 11:18 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
исправил

2020-03-05 11:18 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +            unpaidInv.forEach { unpaid.add(it.invoiceId) }
сделал одной транзакцией

2020-03-05 11:18 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/Datasource.kt
> +    companion object{
теперь передача datasource через конструкторы

2020-03-05 11:19 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBclasses/BtcTxEntity.kt
> +    var Tx by TxEntity referencedOn BtcTxTable.TxId
исправил

2020-03-05 11:19 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +             _tx: TxEntity): BtcTxEntity {
исправлено

2020-03-05 11:20 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/DatabaseCreation.kt
> +    fun createInvoices() {
теперь в папке с тестами

2020-03-05 11:23 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/InvoiceService.kt
> +    fun getInvoices(): ConcurrentHashMap<String, Invoice> {
Хорошо, до появления базы данных изначально у этих полей были такие типы, но по-видимому сейчас лучше действительно выбрать более общий интерфейс

2020-03-05 11:26 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        Datasource.initConnection(databaseConfig)
нет, Datasource инитился в BlockchainPaymentSystemManager. Сейчас все также, только передается потом в конструкторы

2020-03-05 11:31 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +    private val txService = TxService()
Вообще, как мне кажется, на всю программу можно создавать по одному каждому сервису. Раз у нас есть Datasource, доступ к которому теперь везде есть, то можно там создавать и потом все будут брать оттуда.

2020-03-05 11:44 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +            transaction.amount(), transaction.fee(), transaction.hash(), transaction.index(), transaction.currency().toString())
В каком-нибудь участке кода могло потребоваться вызвать этот метод не имея всего Tx. Вроде как таких случаев в итоге не было (хотя когда нибудь могут появиться), но например в тестах, когда мы мокали один адрес, а передавали другой, чтобы посмотреть что не будет перевода, у нас не было нужной сущности Tx, чтобы передать

2020-03-05 11:45 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        btcService.add(it.confirmations, blockHash, it.address, newTx)
выпилил в итоге. Мне она тоже не нужна)

2020-03-05 12:33 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
Нанопридирка, называть enum как Type - оч плохо, ибо сам по себе Type много где появляется в последствии. Лучше так и назвать - PayableType.

2020-03-05 12:52 UTC, phil-dolgolev requested changes
Сейчас неявные заточки на наличие threadlocal transaction Manager везде, что как по мне плохо, нужно явно связывать datasource и транзакции

2020-03-05 12:52 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        datasource.getConnection()
🤔 
Что-то я не очень догоняю как это работает
Вроде как явно connection этот нигде не используется, но зачем-то дергается тут

2020-03-05 12:52 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        datasource.getConnection()
transaction(datasource.getConnection()) {
            if (!BtcTxTable.exists())
                SchemaUtils.create(BtcTxTable)
        }

Кажется, или скорее как-то так должно все строиться?

2020-03-05 12:54 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        val new = TxService(coin.config[DatabaseConfig.connectionURL], coin.config[DatabaseConfig.driver]).add(tx.status().toString(), tx.destination(), tx.tag(), tx.amount(),
@artemlunev2000

2020-03-05 12:57 UTC, phil-dolgolev requested changes

2020-03-05 12:57 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBservices/TxService.kt
> +class TxService(datasource: Datasource) {
Создается много где, когда ничем инстансы не отличаются, выглядит странно, и раньше уже об этом писал. 
Нужно видимо чтоб TxService был Singleton

2020-03-07 11:48 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        datasource.getConnection()
в доке exposed говорят, что формат `transaction(db) {...}` — хорош, когда у нас несколько бд
а если просто `transaction {...}`, то подтягивается последний коннекшн, насколько я понимаю

на счёт того, что он дёргается везде, но не используется — мне тож не понятно
такое ощущение, что будет работать, даже если везде выпилить вызовы `.getConnection()`
кажется, что использование формата, предложенного @phil-dolgolev, добавит гибкости в будущем в использовании нескольких дата-сурсов

2020-03-10 09:25 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBclasses/PayableEntity.kt
> +    var type by PayableTable.type
переименовал

2020-03-10 09:26 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/crypto/btc/BtcExplorer.kt
> +                        val new = TxService(coin.config[DatabaseConfig.connectionURL], coin.config[DatabaseConfig.driver]).add(tx.status().toString(), tx.destination(), tx.tag(), tx.amount(),
теперь TxService создается в менеджере и передается по конструкторам

2020-03-10 09:32 UTC, artemlunev2000 commented on src/main/kotlin/dsx/bps/DBservices/BtcService.kt
> +        datasource.getConnection()
Да, при многопоточке такой вариант тоже должен быть рабочим

2020-03-10 09:44 UTC, phil-dolgolev approved these changes

2020-03-10 09:45 UTC, merged