Bps 25
dsx-tech/Blockchain-Payment-System pull request #19
Opened 2020-02-17 15:57 UTC by siandreev

2020-02-18 13:59 UTC, phil-dolgolev requested changes

2020-02-18 13:59 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +     * @return account balance in ether (15 signs).
Может 15 конфирмейшенов?

(висит со старого PR-а еще этот момент)

2020-02-18 13:59 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +     * @param txid IxId object ( {hash : String, index : Int} )
IxId
(висит со старого PR-а еще этот момент)

2020-02-18 13:59 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +        return object : Tx {
Я правильно понимаю, что здесь создается анонимный класс каждый раз?
Довольно странная штука, почему не запилен именно класс для этого дела, реализующий интерфейс?
(висит со старого PR-а еще этот момент)

2020-02-18 13:59 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        viewed.add(last.hash)
При перезапусках мы не заполняем историю? Это надо как-то обойти

(висит со старого PR-а еще этот момент)

2020-02-18 13:59 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +                    viewed.add(new.hash)
Добавление сразу во viewed означает, что если мы свалимся с ошибкой дальше, то у нас потенциально возникает пропуск блоков, или я что-то не так понял?

(висит со старого PR-а еще этот момент)

2020-02-18 13:59 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +internal class EthRpcTest {
Вот для этого нам и нужны testcontainers, чтобы эти тесты на только руками можно было запускать на определенном локальном энвайроменте, но и на CI

2020-02-19 08:01 UTC, phil-dolgolev requested changes

2020-02-19 08:01 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +    var redis = KGenericContainer("siandreev/ethereum-rpc-test:mining")
Смотреть варианты решений в интернете - хорошо
Копипастить - плохо, лучше руками первые разы переписывать, полезно :)

2020-02-19 08:01 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +    var redis = KGenericContainer("siandreev/ethereum-rpc-test:mining")
Я правильно понимаю - что это бережно созданный руками контейнер твой? 
Он локальный или в dockerhub есть?

Нужно исходить из того, что тесты должны требовать только наличие docker окружения, без завязок на личные кастомные образы.

2020-02-19 08:08 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +    var redis = KGenericContainer("siandreev/ethereum-rpc-test:mining")
На тему локальности - протестил у себя локально - все замечательно, огонь. 
Нужно наверное завести dockerhub под проект и закинуть туда все это дело. 

Ну и в гите наверное надо держать Dockerfile для тестов, потом может вынесем куда.

2020-02-19 15:15 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthCoin.kt
> +        return object : Tx {
https://github.com/dsx-tech/Blockchain-Payment-System/pull/16#discussion_r357854548

2020-02-25 19:01 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +                    viewed.add(new.hash)
Было исправлено тут https://github.com/dsx-tech/Blockchain-Payment-System/pull/19/commits/23e97dc29e0abdc4b1c148cdfd1babbc401e66fe

2020-02-25 19:51 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        viewed.add(last.hash)
Добавил отмотку на 30 блоков перед стартом

2020-03-01 15:24 UTC, skoret requested changes

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +    fun getBlockByHash(hash: String): org.web3j.protocol.core.methods.response.EthBlock.Block {
предлагаю импортить классы, чтобы не нагружать код

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        return tx.filter { it -> it.from == address }.size
полезно иногда обращать внимание на подсказки идеи
в данном случае, например, конструкция `it ->` излишняя, если в качестве обозначения элемента коллекции мы всё равно используем `it`

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +    }
метод явно для тестовых целей да ещё и с захардкоженной константой
предлагаю вынести его реализацию туда, где он действительно нужен
и мб даже сделать конфигурируемым необходимое число ожидаемых блоков

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        while (last.numberRaw.substring(2).toBigInteger(16) != BigInteger.ZERO && scanedBlocks < scaningCount) {
чтобы не мучаться так каждый раз `last.numberRaw.substring(2).toBigInteger(16)`, возможно, стоит набросать свою небольшую обёртку над web3j классом блока, которая внутри себя будет производить такие хитрости

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        var scanedBlocks = 0
опечатка: `scaned` → `scanned`
есть оч приятный плагин [grazie](https://plugins.jetbrains.com/plugin/12175-grazie), поможет с выражением мысли на английском

2020-03-01 15:24 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        while (last.numberRaw.substring(2).toBigInteger(16) != BigInteger.ZERO && scanedBlocks < scaningCount) {
заглянул в `org.web3j.protocol.core.methods.response.EthBlock.Block`
оказывается, там есть метод `EthBlock.Block#getNumber`, который уже реализует то, что хочется
и не нужно изобретать велосипед

2020-03-01 15:24 UTC, skoret commented on src/test/resources/ETH/EthContainer/Dockerfile
> +CMD exec ./geth --minerthreads 1 --datadir="/datadir" --allow-insecure-unlock --rpcapi eth,web3,personal,admin  --password /geth.password --unlock "0" --port 30303 --rpc --rpcaddr "0.0.0.0" --network
законспектирую последние обсуждения, чтобы не пропало:
1. надо разобраться, как запускать ефирную ноду на уже имеющейся истории блоков
2. нагенерить небольшую предысторию с нашими тестовыми аккаунтами и балансами на них
3. заапдейтить контейнеры, чтобы не ждать, пока блоки намайнятся сами, а брались уже готовые
4. проверить, как это понравится тревису

2020-03-01 15:24 UTC, skoret commented on src/test/resources/ETH/EthContainer/datadir/geth/lightchaindata/LOG
> +16:16:04.350260 db@close done T·1.991ms
похоже, что не все файлы, нагенеренные geth'ом необходимы в репозитории
стоит выяснить, что действительно надо заливать в репу, а что можно игнорить (например, логи)
и, соответственно, апдейтнуть `.gitignore` (даже не глобальный, а новый где-нибудь в src/test/resources/ETH, например)

2020-03-02 06:34 UTC, phil-dolgolev requested changes

2020-03-02 06:34 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +            println(bal)
Глобальная нано придирка - выпилить println везде, по возможности заменить на assert-ы.

2020-03-02 06:34 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +            println(bal)
Здесь например можно и assert спокойно сделать, насколько я помню в генезис файле можно указать балансы на конкретных адресах, а тут их можно проверять :)

2020-03-02 06:34 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        viewed.add(last.hash)
А почему именно на 30? Почему хардкод?

2020-03-02 06:34 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +    fun getBlockByHash(hash: String): org.web3j.protocol.core.methods.response.EthBlock.Block {
Если есть пересечение по Block, то не должно быть по EthBlock.Block. Но вообще не зазорно и свои обертки делать, отвязывает от конкретной реализации в либе.

2020-03-02 06:34 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/crypto/eth/EthRpcTest.kt
> +            println(bal)
@siandreev ?

2020-03-02 06:34 UTC, phil-dolgolev commented on src/test/resources/ETH/EthContainer/Dockerfile
> +CMD exec ./geth --minerthreads 1 --datadir="/datadir" --allow-insecure-unlock --rpcapi eth,web3,personal,admin  --password /geth.password --unlock "0" --port 30303 --rpc --rpcaddr "0.0.0.0" --network
Сделаем не в рамках этого PR-а, задачку сделал

2020-03-02 06:34 UTC, phil-dolgolev commented on src/test/resources/ETH/EthContainer/datadir/geth/lightchaindata/LOG
> +16:16:04.350260 db@close done T·1.991ms
Кажется, что все должно быть заигнорено и на старте воспроизведется. @siandreev

2020-03-05 09:07 UTC, siandreev commented on src/test/resources/ETH/EthContainer/datadir/geth/lightchaindata/LOG
> +16:16:04.350260 db@close done T·1.991ms
Исправил путем удаления папки geth, т.к. в скором времени планируется перейти на контейнер, который будет генерить ее внутри себя с помощью genesis.json, а не копировать

2020-03-05 10:39 UTC, phil-dolgolev requested changes

2020-03-05 10:39 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/common/Connector.kt
> +
@DmitryPogrebnoy хе, у вас походу мысли в одну сторону. Имхо, такой нейминг больше подходит.

2020-03-05 10:39 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        var scanedBlocks = 0
@siandreev вот поэтому резолвить автор беседы должен, а то фикса то нет 🙃

2020-03-05 10:39 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        val transactionInfo = web3j.ethGetTransactionByHash(hash).sendAsync().get()
sendAsync().get() выглядит смешно на самом деле, когда есть send()

Вы хоть чуточку смотрите доку/сигнатуры/доступные методы.

2020-03-05 10:39 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        val ethBlock = web3j.ethGetBlockByNumber(
Хе, опять же получаются забавные монстры если доку не читать. 

web3j.ethGetTransactionCount(address, DefaultBlockParameterName.PENDING) - ровно то что ты хочешь 🙃

2020-03-05 10:39 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/api/BlockchainPaymentSystemAPITestBTC.kt
> +        Thread.sleep(10000)
А зачем sleep?

В надежде на поднятие ноды полностью в контейнере? Так это получается стохастический тест, да и к тому же медленный. 

У testcontainers можно например заточиться на ожидание определенной строчки в логах, и через это раскрутить без всяких слипов железобетонно.

2020-03-05 10:39 UTC, phil-dolgolev commented on src/test/kotlin/dsx/bps/api/BlockchainPaymentSystemAPITestBTC.kt
> +        Thread.sleep(10000)
.waitingFor надо раскручивать

2020-03-11 12:31 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        val ethBlock = web3j.ethGetBlockByNumber(
исправил

2020-03-11 12:31 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthRpc.kt
> +        val transactionInfo = web3j.ethGetTransactionByHash(hash).sendAsync().get()
исправил

2020-03-11 12:32 UTC, siandreev commented on src/test/kotlin/dsx/bps/api/BlockchainPaymentSystemAPITestBTC.kt
> +        Thread.sleep(10000)
обновил контейнер и исправил, используя ожидание конкретной строки в логах

2020-03-11 12:38 UTC, siandreev commented on src/test/kotlin/dsx/bps/api/BlockchainPaymentSystemAPITestBTC.kt
>          val invId = aliceAPI.createInvoice(Currency.BTC, 0.42)
Временно отключил, т.к. по-моему с изменениями по обработке инвойсов что-то не так: платеж проходит, но при этом теперь статус платежа почему-то не меняется

2020-03-13 15:38 UTC, siandreev commented on src/main/kotlin/dsx/bps/crypto/eth/EthExplorer.kt
> +        var scanedBlocks = 0
Исправил

2020-04-14 00:15 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/EthService.kt
> +    {
скобка убежала

2020-04-14 00:15 UTC, skoret commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        }
отступы

2020-04-14 00:15 UTC, skoret commented on src/main/resources/smart contract source/proxy.sol
> +pragma solidity ^0.6.4;
бест практис где бы то ни было — не использовать пробелы в названиях директорий/файлов

2020-04-29 12:09 UTC, siandreev commented on src/main/resources/smart contract source/proxy.sol
> +pragma solidity ^0.6.4;
исправил

2020-04-29 12:09 UTC, siandreev commented on src/main/kotlin/dsx/bps/core/BlockchainPaymentSystemManager.kt
> +        }
исправил

2020-04-29 12:09 UTC, siandreev commented on src/main/kotlin/dsx/bps/DBservices/EthService.kt
> +    {
исправил

2020-05-16 11:47 UTC, closed without merging