Bps 24
dsx-tech/Blockchain-Payment-System pull request #21
Opened 2020-03-04 08:45 UTC by DmitryPogrebnoy

Первичная поддержка Gram.
1) Обработка входящих транзакций для сопоставления с Invoice
2) Юнит тесты

2020-03-04 08:52 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    }
Насколько я понял, TonApi не предоставляет возможности взять одну конкретную транзакцию, только список транзакций начиная с некоторой и до самой новой. Поэтому пока непонятно как реализовать этот метод. Есть идеи?
Как вариант брать список транзакций (потенциально очень большой) начиная с нужной транзакции и доставать первую транзакцию из этого списка.

2020-03-04 08:55 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Небезопасный каст Long к Int. Как вариант сменить тип на BigDecimal/Long/String. Интерфейс Tx используется везде, поэтому уточняю.

2020-03-04 15:16 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun tag() = grmTx.inMsg.msgData.body.toString(Charsets.UTF_8).toIntOrNull()
Tag меняем тип на String

2020-03-04 15:17 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Да, переходим к Long.

2020-03-05 08:54 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    }
Тут вроде как скорее позволяет взять от конкретной транзакции в прошлое :) 
Очно обсуждали, что обнаружение транзакций и складывание в базу отдельно будет, и на основе базы будут тут возвращаться значения.

2020-03-05 09:19 UTC, skoret commented on build.gradle
> +    systemProperty 'java.library.path', file( 'src/main/jniLibs' )
такие штуки в resources давайте

2020-03-05 09:19 UTC, skoret commented on src/main/kotlin/dsx/bps/connection/Connection.kt
> +}
тут надо будет засинкаться/замёржиться с пр'ом @siandreev, у него появился один-в-один `Connector`
давайте, наверно, это имя и оставим, т.к. `Connection` больше в сторону работы с db

2020-03-05 09:19 UTC, skoret commented on src/main/kotlin/dsx/bps/connection/Connection.kt
> +}
когда #19 замёржится, подлей к себе изменения с резолвом конфликтов

2020-03-05 10:03 UTC, phil-dolgolev requested changes

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +    override val connection: BtcRpc
Только это скорее connector :)

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun hash() = grmTx.transactionId.hash.toString()
А вот тут выглядит как косяк. 
1) toString() у массива хз какой
2) Даже если создавать как строку с кодировкой - все еще дичь


Здесь нужно конвертировать байты в хекс - это единственное верное решение. 
А еще предлагаю сравнивать то что парсится в коде с тем, что можно посмотреть в liteClient-е

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Странная штука

LT - LogicTime, некоторые виртуальные часы глобальные в блокчейне. Никакого отношения к index() не имеют. Index - вообще чисто про битковые истории, ну, точнее про истории с входами/выходами. Раз путает, надо будет потом выпилить index из общего интерфейса, и оставить только для битка.

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun tag() = grmTx.inMsg.msgData.body.toString(Charsets.UTF_8).toIntOrNull()
Ну и само название tag я бы поменял.

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun status() = TxStatus.CONFIRMED
Это верно только для депозитов по идее.

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        tonClient = TonClient.create(null, null, null)
Вместо null-ов яб добавил базовое логирование просто

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +            ), null, null
Вместо null-ов яб добавил базовое логирование просто

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        var fullAccountState: TonApi.FullAccountState = TonApi.FullAccountState()
А зачем инитить пустым объектом ?)

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        var rawTxs: TonApi.RawTransactions = TonApi.RawTransactions()
Там есть нюансик, что вроде как возвращает максимум 10 транзакций. Или вообще 5. 
Значит нужно более интелектуально это делать :)

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                coin.getAccountTxs(lastTxId).filter {
Чисто теоретически, если придет сообщение с каким-то кривым телом что наш контракт его отопнет - то мы начислил бабосики, но их не будет. 

Нужно здесь более аккуратно это все дело считать, и по идее тут должен быть где-то явно передан основной аккаунт относительно которого мониторим движуху.

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmBlockIdExt.kt
> +    override fun equals(other: Any?): Boolean {
А зачем тут явно сгенерены эти методы? Вроде как в котлине же data классы сразу генерят equals/hashcode в зависимости от полей.

2020-03-05 10:03 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmInternalTxId.kt
> +    val hash: ByteArray
Вот раз тут ты решил действительно изолироваться своими объектами, то в них уже можно и конвертации делать нужные себе, например хэш из байтов в строку сконвертировать.

2020-03-07 12:23 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun tag() = grmTx.inMsg.msgData.body.toString(Charsets.UTF_8).toIntOrNull()
payment reference? 😄

2020-03-09 07:22 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    }
Жду BPS-6

2020-03-09 07:41 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
У Tx есть index: Int и hash, и у TxId есть index: Int и hash. По умолчанию значения index и hash в TxId берется из значения index и hash в Tx. Транзакция аккаунта в ton идентифицируется с помощью пары значений хеша и lt, эти значения и записываются в hash и в index соответственно. Действительно, можно не использовать index в Tx и конструировать напрямую TxId, но одинаковое название полей сбивает с понимания назначения каждого из них.

2020-03-09 07:51 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Но подождите, в реализации constructTx в XrpCoin index используется для хранения sequence, что, как мне кажется, очень близко к LT в ton. Так что мне по-прежнему кажется, что все используется верно, т.к. index для каждой валюты имеет свою интерпретацию.

2020-03-09 08:02 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun tag() = grmTx.inMsg.msgData.body.toString(Charsets.UTF_8).toIntOrNull()
Да, пусть будет paymentReference. В Payment и в Invoice так и останется tag.

2020-03-09 08:37 UTC, DmitryPogrebnoy commented on build.gradle
> +    systemProperty 'java.library.path', file( 'src/main/jniLibs' )
Окей, давай)

2020-03-09 08:39 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/connection/Connection.kt
> +}
Заменил Connection на Connector.

2020-03-09 08:39 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/btc/BtcCoin.kt
> +    override val connection: BtcRpc
Поправил

2020-03-09 11:42 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun hash() = grmTx.transactionId.hash.toString()
Да, действительно косяк. Поправил и протестил, результат теперь сходится.

2020-03-09 12:01 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        tonClient = TonClient.create(null, null, null)
Базовое логирование это println? :)
Правильно я понимаю, что по идее нужны три объекта реализующие необходимый интерфейс?

2020-03-09 12:01 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +            ), null, null
Базовое логирование это println? :)
Правильно я понимаю, что по идее нужны три объекта реализующие необходимый интерфейс?

2020-03-09 12:16 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        var fullAccountState: TonApi.FullAccountState = TonApi.FullAccountState()
Оу, странный косяк.

2020-03-09 13:10 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmInternalTxId.kt
> +    val hash: ByteArray
Да, действительно. Тогда уж все остальные массивы байт в хексовые строки можно перегонять.

2020-03-09 13:17 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmBlockIdExt.kt
> +    override fun equals(other: Any?): Boolean {
data классы генерят методы автоматически только если в них нет массивов (здесь массивы байт). Поэтому нужно было сгенерить вручную. Теперь, раз все хеши представлены в хексовых строках, то функции сгенерятся автоматически компилятором и в исходном коде они не нужны.

2020-03-09 16:54 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        var rawTxs: TonApi.RawTransactions = TonApi.RawTransactions()
Действительно, максимум 10 транзакций. И не начиная с текущей транзакции и новее, а начиная с текущей транзакции и старее. Мне все меньше и меньше нравится api :(
Внесу нужные правки в эту функцию и в grmExplorer.

2020-03-09 17:04 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                coin.getAccountTxs(lastTxId).filter {
Здесь мы просматриваем только транзакции. Значит они уже применены и вся валюта начислена. Если придет сообщение с кривым телом и контракт его отопнет, то максимум будет транзакция с 0 value (или не будет транзакции вообще) которая отсеется на `coin.getAccountTxs(lastTxId).filter{...}`

Адрес основного аккаунта относительно которого мониторим транзакции передается в методах `coin: grmCoin`

2020-03-09 17:07 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun status() = TxStatus.CONFIRMED
Для депозитов точно верно, для вывода средств нужно думать и в целом разобраться с процессом вывода.

2020-03-10 08:29 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    }
Можно пока складывать в список в памяти, потом уже в базу пихать после мержа BPS-6

2020-03-10 08:32 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Значит с Xrp проглядел в свое время. Не надо продолжать насиловать это поле и пихать разные штуки в него. Это чисто специфичные штуки для конкретного чейна, и предлагаю явно это разделять и не просачивать наружу. В общем, с TON-ом уже переделываем, потом зафиксим для Xrp (тикет можем завести на это дело).
@skoret @DmitryPogrebnoy что скажете?

2020-03-10 08:36 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                coin.getAccountTxs(lastTxId).filter {
А вот и не правда :) Предлагаю сбоку провести эксперимент - закинуть деньги на непроиниченный адрес с флагом bounce. В inMsg будет ровно та же сума, будет транза, и появится out message с почти этой же суммой. Т.е. на балансе будет 0, а при текущем парсинге будет будтво денег завели на аккаунт. И еще вопрос что будет с исходящим сообщением и как оно распарсится.

2020-03-10 08:37 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmBlockIdExt.kt
> +    override fun equals(other: Any?): Boolean {
Как поправишь, можно зарезолвить эту штуку

2020-03-10 08:37 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmInternalTxId.kt
> +    val hash: ByteArray
Как поправишь - зарезолви плз

2020-03-10 12:07 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
То есть в случае с TON-ом игнорирует index в Tx и проставляем index только в TxId?

2020-03-11 09:54 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
С TxId - немного сложно, но пока видимо так, да. Надо еще посмотреть как работают эксплолеры, каких данных им достаточно, например gramscan.io, и еще была парочка любительских.

2020-03-11 11:11 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +            override fun index() = grmTx.transactionId.lt.toInt()
Хорошо, гляну эксплореры на https://github.com/copperbits/awesome-ton

2020-03-16 07:24 UTC, phil-dolgolev requested changes

2020-03-16 07:24 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/DBclasses/GrmTxTable.kt
> +    val storageFee: Column<Long> = long("storageFee")
А storageFee зачем выделять отдельно то?

2020-03-17 16:10 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                coin.getAccountTxs(lastTxId).filter {
Поправил explorer. Теперь кажется все как надо.

2020-03-17 16:13 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/DBclasses/GrmTxTable.kt
> +    val storageFee: Column<Long> = long("storageFee")
stroageFee пока просто чтобы был, если он так и не понадобится, то можно будет убрать

2020-03-18 13:06 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    }
Раз TonApi позволяет возвращать макс 10 транзакций аккаунта с текущей, то нет проблем с тем, чтобы запрашивать транзакцию по сети, что я и реализовал. Или все-таки зацикливаем все на БД и ищем транзакцию в бд, а не запрашиваем по сети?

2020-03-18 13:07 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmConnection.kt
> +        var fullAccountState: TonApi.FullAccountState = TonApi.FullAccountState()
Поправил.

2020-03-29 16:08 UTC, phil-dolgolev approved these changes

2020-03-29 16:08 UTC, merged