BPS-24
dsx-tech/Blockchain-Payment-System pull request #23
Opened 2020-04-03 09:27 UTC by DmitryPogrebnoy

Реализовал отправку платежей.
С отслеживанием статуса платежей пока непонятно. Процесс отслеживания платежа плохо ложиться на архитектуру paymentProcessor.

2020-04-05 19:42 UTC, DmitryPogrebnoy commented
Нашел оптимальное решение, но нужно еще написать тесты.

2020-04-06 16:01 UTC, DmitryPogrebnoy commented
Доделал отправку платежей и отслеживание их статуса. Написал юнит тесты. Отправку на реальных переводах не тестировал, т.к. сеть пока лежит. Но смотреть код уже можно. 
Также поправил гонку в InvoiceProcessor.

2020-04-13 23:59 UTC, skoret requested changes

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    override fun updatePaymentTxStatus(txid: TxId): Tx {
здесь `updatePaymentTxStatus` только для выплат, а `getTx` только для депозитов/счетов?
правильно понимаю, что для grm нам всегда необходимо выполнять такой "update", когда мы спрашиваем у ноды транзу?

если да, то предлагаю оставить `GrmCoin#updatePaymentTxStatus` приватным методом и дёргать его внутри `getTx` в зависимости от направления транзакции
так у нас не будет метода в общем интерфейсе, который нельзя дёргать нигде, кроме `PaymentProcessor`

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +        if (grmTx.inMsg.source != "") {
наноминор-предложение
```suggestion
        if (grmTx.inMsg.source.IsEmpty()) return
```

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                (tx.paymentReference()?.length ?: -1) < 500
магические константы стоит выносить в приватные константы класса с поясняющими именами

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +            val tx = coin.constructDepositTx(grmTx)
правильно понимаю, что `if` на предыдущей строчке даёт нам гарантию, что данная транза — входящая?

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmRawMessage.kt
> +    override fun toString(): String {
а почему бы не `data class`, как предыдущие?

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmRawTransaction.kt
> +    override fun toString(): String {
и туть `data`

2020-04-13 23:59 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    fun getAccountTxs(
особые значения для `olderAccountTxs.previousTransactionId.lt` и `olderAccountTxs.previousTransactionId.hash` тоже в константы класса

2020-04-15 07:18 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +            val tx = coin.constructDepositTx(grmTx)
В `GrmExplorer` обрабатываются только internal сообщения, т.е. сообщения которые имеют аккаунта-отправителя и потенциально могут заматчится с некоторым  `Invoice`. `if` на предыдущей строчке дает гарантию, что будут отброшены external сообщения, т.е. сообщения у которых нет аккаунта отправителя. Отсутствие аккаунта-отправителя означает, что входящее сообщение не связано с `Invoice` и такое сообщение обрабатывать не не нужно.

2020-04-15 08:45 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmRawMessage.kt
> +    override fun toString(): String {
Поправил

2020-04-15 08:45 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/datamodel/GrmRawTransaction.kt
> +    override fun toString(): String {
Поправил

2020-04-15 09:00 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    fun getAccountTxs(
Поправил

2020-04-15 09:02 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +        if (grmTx.inMsg.source != "") {
Окей, поправил)

2020-04-15 09:15 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                (tx.paymentReference()?.length ?: -1) < 500
Точно, просмотрел этот момент

2020-04-15 11:19 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    override fun updatePaymentTxStatus(txid: TxId): Tx {
1) `updatePaymentTxStatus` только для `Payment` - это да. `getTx` используется И для депозитов/счетов. То есть использовать `updatePaymentTxStatus` в других местах кроме как в PaymentProcessor нельзя, а использовать `getTx` везде, где захочется можно. Нужно еще отметить, что getTx может вернуть транзакции только "нашего" аккаунта, а не любого.
2) Для grm нам всегда нужно выполнять такой "update" только когда мы запрашиваем состояние транзакции "Payment", т.е. в `PaymentProcessor#check()`. Для запроса транзакций `Invoice` и для получения транзакции "нашего" аккаунта с помощью метода `GrmCoin#getTx()` "update" делать не нужно.

Кажется, что getTx имеет две функции. Первая api - получить транзакцию из сети по txid, а вторая для InvoiceProcessor- получить транзакцию Invoice'a из сети. Если так, то мб стоит разделить функцию getTx() на две?

3)
> если да, то предлагаю оставить GrmCoin#updatePaymentTxStatus приватным методом и дёргать его внутри getTx в зависимости от направления транзакции
так у нас не будет метода в общем интерфейсе, который нельзя дёргать нигде, кроме PaymentProcessor

Что означает "в зависимости от направления транзакции"? По `TxId` мы можем только запросить транзакцию ничего не зная о ее принадлежности к `Invoice` или `Payment`. Можно запоминать, в GrmCoin какие TxId "нашего" аккаунта относятся к Payment и каждый раз в getTx() матчится по ним. Если мы заматчимся удачно, то вызываем `GrmCoin#updatePaymentTxStatus`, иначе запрашиваем транзакцию по сети.

Я понимаю, что это плохо, когда так торчит ненужный метод, но идей как сделать по-другому у меня нет.

На всякий случай опишу процесс обработки `Payment`.

- Вызывается метод `sendPayment`. Сначала мы запоминаем в бд `txid` последней  транзакции целевого аккаунта(того куда переводим валюту). Далее мы отправляем external сообщение на свой аккаунт: "переведи столько-то грам на такой-то адрес". Если это сообщение удачно обработано, то в результате его обработки из нашего аккаунта появляется исходящее internal сообщение на целевой адрес с необходимым количеством валюты. Мы формируем и возвращаем транзакцию о переводе средств со статусом `TxStatus.VALIDATING`.

- Далее нужно убедится, что internal сообщение корректно обработалось на целевом аккаунте и возврата средств нет. Для этого используется метод `GrmCoin#updatePaymentTxStatus(txid: TxId)`. В нем мы по переданному аргументу `txid` запрашиваем транзакцию с нашего аккаунта. Из этой транзакции получаем адрес целевого аккаунта. Далее достаем из бд txid последней транзакции целевого аккаунта (т.к. раньше этой транзакции искать обработку нашего internal сообщения нет смысла). Получаем из сети все транзакции целевого аккаунта, которые нужно проверить. Ищем среди них транзакцию в которой обработалось отправленное internal сообщение с нашего аккаунта. Если нашли и обработка сообщения прошла успешно - возвращаем транзакцию со статусом `TxStatus.CONFIRMED`, если обработка прошла с ошибкой - возвращаем транзакцию со статусом `TxStatus.REJECTED`, если не нашли транзакцию - обновляем запись в бд и возвращаем транзакцию со статусом TxStatus.VALIDATING.

2020-04-15 11:59 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                (tx.paymentReference()?.length ?: -1) < 500
Поправил

2020-04-18 19:29 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +    override fun updatePaymentTxStatus(txid: TxId): Tx {
Логика отслеживания платежей упрощена. Лишние методы больше не торчат.

2020-04-24 06:18 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +            val tx = coin.constructDepositTx(grmTx)
Теперь в `GrmExplorer` сохраняются в бд все транзакции аккаунта.

2020-04-24 11:39 UTC, skoret requested changes

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/DBclasses/crypto/grm/GrmOutMsgTable.kt
> +    val destination: Column<String> = GrmInMsgTable.varchar("sourceAddress", 1024)
копипаста затесалась

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/DBservices/crypto/grm/GrmTxService.kt
> +                GrmTxTable.txId eq TxTable.id and (TxTable.index eq TxTable.index.max())
а тут нам правда вернётся самая новая grm транзакция, даже если после неё были транзакции какой-то другой валюты и у них `TxTable.index` больше?

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/core/PaymentProcessor.kt
> +                            }
минор
как вариант, чтобы не писать одно и то же:
```suggestion
                            TxStatus.REJECTED, TxStatus.INCORRECT -> {
                                txService.updateStatus(tx.status(), tx.hash(), tx.index())
                                payService.updateStatus(PaymentStatus.FAILED, pay.id)
                                pay.status = PaymentStatus.FAILED
                                // add this payment to resend list if needed
                            }
```

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +                    return txService.constructTxByTxEntity(grmTx.tx)
а правильно понимаю, что здесь статус `CONFIRMED` и в последней строчке метода статус `INCORRECT` — уже проставлены в самом `grmTx.tx`? кажется, что да
в таком случае предлагаю снижать вложенность кода (if'ов) для удобочитаемости
расписывать словами долго, поэтому примерно так:
```kotlin
    if (grmTx == null) {
        return if (...) { ... } else { ... }
    }
    if (grmOutMsgService.getOutMsgs(grmTx.id).size == 1) {
        if (grmTx.tx.destination != txEntity.destination ||
            grmTx.tx.tag != txEntity.tag ||
            grmTx.tx.amount != txEntity.amount) {
                // if outMsg is not valid - status INCORRECT
                return object: Tx { ... }
        }
    }
    // if grmTx has one outMsg and outMsg is valid - status CONFIRMED
    // if grmTx has zero or more then one outMsg - status INCORRECT
    return txService.constructTxByTxEntity(grmTx.tx)
```

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
>      private val txService = txServ
тож минорная штука — такие нехитрые инициализации можно в принципе выносить сразу в праймари конструктор, как с `val coin`

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +        } else if (grmTx.inMsg.source != "" && grmTx.inMsg.msgText.length <= tagMaxLength) {
тоже минорчик — мы сюда попадём, только если `!grmTx.inMsg.source.isEmpty()`, значит в проверке на `!= ""` не нуждаемся

2020-04-24 11:39 UTC, skoret commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                    if (grmOutMsg.msgText.length <= tagMaxLength) {
мы не запишем in/out сообщения, если длина `msgText` больше максимума
чем нам это грозит?

2020-04-25 13:35 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/DBclasses/crypto/grm/GrmOutMsgTable.kt
> +    val destination: Column<String> = GrmInMsgTable.varchar("sourceAddress", 1024)
Поправил

2020-04-25 13:45 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/DBservices/crypto/grm/GrmTxService.kt
> +                GrmTxTable.txId eq TxTable.id and (TxTable.index eq TxTable.index.max())
Поправил. Теперь в выборке учитываем валюту.

2020-04-25 13:49 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/core/PaymentProcessor.kt
> +                            }
Действительно так лучше, поправил

2020-04-25 14:20 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmCoin.kt
> +                    return txService.constructTxByTxEntity(grmTx.tx)
Исправил, читается действительно лучше :)

2020-04-25 14:23 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
>      private val txService = txServ
Да, поправил

2020-04-25 14:24 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +        } else if (grmTx.inMsg.source != "" && grmTx.inMsg.msgText.length <= tagMaxLength) {
Поправил

2020-04-25 16:45 UTC, DmitryPogrebnoy commented on src/main/kotlin/dsx/bps/crypto/grm/GrmExplorer.kt
> +                    if (grmOutMsg.msgText.length <= tagMaxLength) {
Это грозит тем что логика будет ломаться. Исправил это. Теперь при очень больших данных будем подменять их на "значение по умолчанию".

2020-04-26 15:43 UTC, skoret approved these changes

2020-04-27 17:09 UTC, merged