first implementation of bitcoin module
dsx-tech/Blockchain-Payment-System pull request #4
Opened 2019-02-12 12:51 UTC by skoret

2019-02-19 08:54 UTC, PhilippDolgolev commented
Рекомендую таки немного переделать схему package-ей
* Core - общая логика для всей крипты, и не гнушайся создавать интерфейсы в первую очередь, абстрактные классы всегда успеешь добавить, а вот избавиться от них бывает сложно и больно. И тут скорее логика по обработке балансов, оплат и инвойсов, работа с БД
* Crypto
* * Common - тут всякие листенеры и прочие классы/интерфейсы уже зависимые от крипты
* * * BTC
* * * * datamodel (aka primitives)
* * * Ripple
* * * * datamodel (aka primitives)

2019-02-19 11:08 UTC, phil-dolgolev requested changes

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/btc/BtcBlockchainListener.kt
> +                Executors.newSingleThreadExecutor().execute { notifyObservers(listSinceBlock.transactions) }
1) Почему в отдельном потоке?
2) Зачем каждый раз создавать экзекьютор?
3) Но коли создаёшь, то почему не чистишь за собой? Потоками же всё засорится.

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/btc/BtcInvoiceListener.kt
> +        if (arg !is List<*>)
Класс-касты на пустом месте, от этого точно стоит избавиться, надо тут строгую типизацию

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/btc/BtcInvoiceListener.kt
> +                    tx.category == "receive") {
Такого плана строчки как минимум в константы лучше вытаскивать

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/btc/BtcClient.kt
> +        val payment = Payment(currency, outputs, txid)
Здесь нет никаких зачатков по обработке кейса с отваливанием коннекшена во время sendRawTransaction(), обсуждали же проблемы этого кейса

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/Payment.kt
> +    val txIds: MutableList<String> = mutableListOf()
Со списком не понял, тем более mutable, мы же все выводы делаем как одну транзакцию?
Более того, хочется здесь так же трекать комиссию уплаченную в сеть.

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/Payment.kt
> +        this.txIds.addAll(txIds)
На будущее, должно быть консистентно, либо везде пиши this.field либо не пиши :)

2019-02-19 11:08 UTC, phil-dolgolev commented on src/main/kotlin/dsx/bps/core/CoinClient.kt
> +    protected val invoices: HashMap<String, Invoice> = HashMap()
Здесь есть проблемы с concurrency, т.к. нет никаких примитивов синхронизации и специфика Java Memory Model
Пример: после обновления инвойса в чекере в других потоках не гарантируется отображение этих изменений, и могут быть вполне неконсистентные данные. Рекомендую для начала осилить - https://habr.com/ru/post/440590/

2019-02-19 15:40 UTC, skoret commented on src/main/kotlin/dsx/bps/core/Payment.kt
> +    val txIds: MutableList<String> = mutableListOf()
поправил в целом конструирование payment

2019-02-19 15:40 UTC, skoret commented on src/main/kotlin/dsx/bps/btc/BtcClient.kt
> +        val payment = Payment(currency, outputs, txid)
зачатки появились, максимально вдумчивая и аккуратная обработка чуть позже

2019-02-19 18:46 UTC, PhilippDolgolev commented on src/main/kotlin/dsx/bps/btc/BtcClient.kt
> +        val payment = Payment(currency, outputs, txid)
Ок, залепи тудушку и потом зафиксишь

2019-02-19 18:56 UTC, PhilippDolgolev commented on src/main/kotlin/dsx/bps/core/Payment.kt
> +    lateinit var txId: String
Что-то кажется тут намудрено, разве без этого не компилится?

2019-02-19 19:12 UTC, skoret commented on src/main/kotlin/dsx/bps/core/Payment.kt
> +    lateinit var txId: String
не компилится
поле должно быть либо проинициализировано, либо быть абстрактным
а т.к. сами значения txId, fee и rawTx получаем только после некоторой работы над конструированием транзакции, то инициализация полей происходит позже.
как вариант - можно сделать их nullable, если от этого будет какой-то профит

2019-03-04 08:50 UTC, phil-dolgolev approved these changes

2019-03-04 08:50 UTC, merged